name: educate_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_action_sheet: ^1.0.6
  image_picker: ^0.6.7+4
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - images/car.png
    - images/help.png
    - images/think.png
    - images/idea.png
    - images/kougaku.jpg
    - images/JapanArchi.jpg
    - images/scienceNote1.jpg
    - images/MathNote1.jpg
    - images/mathNote2.jpg
    - images/hisNote1.jpg
    - images/appstore.png